server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/movies
    username: postgres
    password: Andy1964
  liquibase:
    change-log: classpath:/db.changelog/db.changelog-master.xml
    url: jdbc:postgresql://localhost:5433/movies
    user: postgres
    password: Andy1964
    driver-class-name: org.postgresql.Driver
